blank_issues_enabled: false
contact_links:
  - name: P2 Forum Community Support
    url: https://forums.parallax.com/discussion/173429/visual-studio-code-supports-p2-development-on-windows-mac-linux-yes-rpi#latest
    about: Discuss the P2 VSCode extension here.

